#!/bin/sh

export PATH=$PATH:/opt/IBM/DB2/bin
basedir=$(dirname `which $0`)

cd ${basedir}
db2 create database travel 

## Crate tables and load data
db2 list database directory

db2 << !
connect to travel

-- Clean up
drop table hotel
drop table rentalcar

-- Create Tables
CREATE TABLE HOTEL (BOROUGH VARCHAR(15), PRICE INT, NAME VARCHAR(60), SERVICE VARCHAR(70), NUM_RATIN INT, RATING INT, LOCATION VARCHAR(15))
CREATE TABLE RENTALCAR (BOROUGH VARCHAR(15), MODEL VARCHAR(30), SIZE VARCHAR(15), RENT INT, AGENCY VARCHAR(10), AGENCYADDR VARCHAR(65), AGENCYPHONE VARCHAR(12)) 

-- Load data to table 
import from /tmp/Hotels3.csv of del replace into HOTEL
import from /tmp/RentalCar1.csv of del replace into RENTALCAR

-- Add columns to sync data
ALTER TABLE HOTEL ADD COLUMN ACCOUNT_NUM SMALLINT NOT NULL DEFAULT 0
ALTER TABLE RENTALCAR ADD COLUMN ACCOUNT_NUM SMALLINT NOT NULL DEFAULT 0
ALTER TABLE RENTALCAR ADD COLUMN SIZEID SMALLINT NOT NULL DEFAULT 0

-- Update records
UPDATE RENTALCAR SET SIZEID = 1 WHERE SIZE = 'Economy'
UPDATE RENTALCAR SET SIZEID = 2 WHERE SIZE = 'Compact'
UPDATE RENTALCAR SET SIZEID = 3 WHERE SIZE = 'Midsize'
UPDATE RENTALCAR SET SIZEID = 4 WHERE SIZE = 'Midsize SUV'
UPDATE RENTALCAR SET SIZEID = 5 WHERE SIZE = 'Standard SUV'
UPDATE RENTALCAR SET SIZEID = 6 WHERE SIZE = 'Minivan'
UPDATE RENTALCAR SET SIZEID = 7 WHERE SIZE = 'Fullsize SUV'
UPDATE RENTALCAR SET SIZEID = 8 WHERE SIZE = 'Fullsize'
UPDATE RENTALCAR SET SIZEID = 9 WHERE SIZE = 'Premium'
UPDATE RENTALCAR SET SIZEID = 10 WHERE SIZE = 'Luxury'
UPDATE RENTALCAR SET SIZEID = 11 WHERE SIZE = 'Convertible'
disconnect travel
!
